name: terang_bulan_zaini
description: "Aplikasi Pemesanan Terang Bulan Pak Zaini"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  get: ^4.6.6

  # --- Cloud Backend & Auth ---
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^5.1.0

  # --- Networking ---
  dio: ^5.3.0

  # --- UI & Utilities ---
  intl: ^0.18.1
  google_fonts: ^6.1.0
  badges: ^3.1.2

  # --- FITUR BARU (Revisi Besar) ---
  image_picker: ^1.1.2 # Untuk Admin ambil gambar
  geolocator: ^13.0.1 # Untuk lokasi pengguna
  geocoding: ^3.0.0 # Opsional, pendukung lokasi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
