name: terang_bulan_zaini
description: "Aplikasi Pemesanan Terang Bulan Pak Zaini"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^5.1.0
  dio: ^5.3.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  badges: ^3.1.2
  image_picker: ^1.1.2 # Untuk Admin ambil gambar
  geolocator: ^13.0.1 
  geocoding: ^3.0.0 
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^16.0.4
  firebase_core: ^4.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
